name: First Workflow
on: workflow_dispatche
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Say Goodbye
        run: echo "All right, bye then."
  
