name: First Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello World"
          echo "Another sentence"
          echo "And the last one"
      - name: Say Goodbye
        run: echo "All right, bye then."
  
